[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
contracts = "CsDdFwNH8mW29B5LMq2VnBfENw7e6VrWVMygEMMMSpsM"

[programs.localnet]
contracts = "CsDdFwNH8mW29B5LMq2VnBfENw7e6VrWVMygEMMMSpsM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
